name: snapshot-exclude-demo
base: core22
version: '0.1'
summary: Snapshot exclusion demo
description: |
  Demonstrate the use of snapshots by providing commands to create 
  system and user data that will be filtered according to the build time 
  exclusions defined in meta/snapshots.yaml in the snapshot filesystem

grade: devel
confinement: devmode

apps:
  bash:
    command: bin/bash.sh      
    plugs: 
      - home

  create-system-data:
    command: bin/create-system-data.sh
    plugs:
      - home

  create-user-data:
    command: bin/create-user-data.sh
    plugs:
      - home

parts:
  data-creation:
    source: source/
    plugin: dump
    organize:
      bash.sh: bin/
      create-system-data.sh: bin/
      create-user-data.sh: bin/
      
  snapshot-exclusions:
    source: config/
    plugin: dump
    organize:
      snapshots.yaml: meta/
